version: "3"

services:
  api-db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fincheck
    ports:
      - "5432:5432"
    volumes:
      - api-db:/var/lib/postgresql/data

volumes:
  api-db:
